### ISSUE TITLE
config_vcr is no where to be found

### ISSUE THREAD

**Issue by ChenghaoMou** [uclanlp/visualbert#3]
I am running the following command:

```
python train.py --folder log --config ../configs/vcr/fine-tune-qa.json
```
```
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from visualbert.dataloaders.vcr import VCR, VCRLoader
  File "/auto/nlg-05/chengham/third-party/visualbert/dataloaders/vcr.py", line 20, in <module>
    from dataloaders.box_utils import load_image, resize_image, to_tensor_and_normalize
  File "/auto/nlg-05/chengham/third-party/visualbert/dataloaders/box_utils.py", line 8, in <module>
    from config_vcr import USE_IMAGENET_PRETRAINED
ModuleNotFoundError: No module named 'config_vcr'
```

I searched the whole repo and cannot find the file.

**Comment by liunian-harold-li** [comment]
Sorry that I forgot to comment this out. Could you change the corresponding line to 

USE_IMAGENET_PRETRAINED = True

?
Sorry for the inconvenience!

**Comment by ChenghaoMou** [comment]
Thanks!
