### ISSUE TITLE
The ROIAlign module used in VCR experiments crushes when forwarding

### ISSUE THREAD

**Issue by yangapku** [uclanlp/visualbert#4]
Hi, I am running the experiments on VCR following the instructions in the readme. I have installed the customed torchvision and detectron modules. However, when the COCO pre-training process  begins, the program is terminated by segmentation fault while the tensors forward the ROIAlign module. Could you help me to figure out this issue? Thank you very much!

**Comment by liunian-harold-li** [comment]
Hi, I ran into this issue as well. Most likely there is some inconsistency in the system environments. I recommend referring to https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/TROUBLESHOOTING.md. 

In case you ran into another environment error, I also referred to https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#troubleshooting.

**Comment by yangapku** [comment]
Thank you! I have solved the problem by upgrading GCC and re-compile the torchvision package. But sadly, some other errors occurred during the validation after training for an epoch. I am still looking into this.

**Comment by liunian-harold-li** [comment]
Glad to hear that training runs okay!

Sometimes I run into issues during the validation because I used multi-processes to read in files and that may take up some system resources (e.g. open files). That may exceed the system limit. Maybe you could try changing the validation worker number to 0?

**Comment by yangapku** [comment]
The error occurs in the validation stage when pre-training on VCR. I commented several lines in the ending of `train.py` to display the detailed error information:
```
#    except:
#        if not args.get("skip_training", False):
#            train_model.save_checkpoint(args.folder, epoch_num, None, is_best=False)
#        print("Something Went Wrong with Evaluation. Ignored.")
#        if args.get("skip_training", False):
#            assert(0)
```
The error information is displayed like the following:
```
 60%|█████▉    | 3967/6634 [1:12:48<33:49,  1.31it/s]Traceback (most recent call last):
  File "train.py", line 292, in <module>
    for b, (time_per_batch, batch) in enumerate(time_batch(val_loader if args.no_tqdm else tqdm(val_loader), reset_every=ARGS_RESET_EVERY)):
  File "/apsarapangu/disk3/yangan.ya/visualbert/utils/pytorch_misc.py", line 30, in time_batch
    for i, item in enumerate(gen):
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/apsarapangu/disk3/yangan.ya/conda/envs/visualbert/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
```
I will try to change the validation worker number to 0 and run again.
